import type { RewriteResult } from "./types"

export function rewriteBullet(
  bullet: string
): RewriteResult {
  return {
    originalText: bullet,
    rewrittenText:
      "Achievement-focused rewrite will be generated by AI in the next integration phase.",
    explanation:
      "Bullet rewrite placeholder.",
    estimatedImprovement: 8,
  }
}
