import type { RewriteResult } from "./types"

export function rewriteSummary(
  summary: string
): RewriteResult {
  return {
    originalText: summary,
    rewrittenText:
      "Professional summary rewrite will be generated by AI in the next integration phase.",
    explanation:
      "Summary rewrite placeholder.",
    estimatedImprovement: 10,
  }
}
