import type { ModuleConfig } from "@/types/modules"

export const modulesConfig: ModuleConfig[] = [
  {
    key: "resume_builder",
    name: "Resume Builder",
    description: "Create, edit, save, and export professional resumes.",
    enabled: true,
    requiredTier: "free",
    usageLimitKey: "resumeUploadsPerMonth",
  },
  {
    key: "resume_library",
    name: "Resume Library",
    description: "Manage saved resumes, versions, duplicates, and history.",
    enabled: true,
    requiredTier: "free",
    usageLimitKey: "resumeUploadsPerMonth",
  },
  {
    key: "job_description_library",
    name: "Job Description Library",
    description: "Save job descriptions for ATS scans and job-search workflows.",
    enabled: true,
    requiredTier: "free",
  },
  {
    key: "career_crm",
    name: "Career CRM",
    description: "Manage recruiters, hiring managers, mentors, and networking contacts.",
    enabled: true,
    requiredTier: "starter",
  },
  {
    key: "ai_resume_parser",
    name: "AI Resume Parser",
    description: "Import resumes and structure sections with AI assistance.",
    enabled: true,
    requiredTier: "starter",
    usageLimitKey: "aiCreditsPerMonth",
  },
  {
    key: "ats_scoring",
    name: "ATS Scoring",
    description: "Score resumes against job descriptions and identify gaps.",
    enabled: true,
    requiredTier: "starter",
    usageLimitKey: "atsScansPerMonth",
  },
  {
    key: "job_tracker",
    name: "Job Tracker",
    description: "Track job applications, interviews, follow-ups, and history.",
    enabled: true,
    requiredTier: "starter",
    usageLimitKey: "trackedJobs",
  },
  {
    key: "job_match_engine",
    name: "Job Match Engine",
    description: "Compare roles, resumes, keywords, and readiness signals.",
    enabled: true,
    requiredTier: "starter",
    usageLimitKey: "atsScansPerMonth",
  },
  {
    key: "ai_interviewer",
    name: "AI Interviewer",
    description: "Practice mock interviews with AI-generated prompts and feedback.",
    enabled: true,
    requiredTier: "pro",
    usageLimitKey: "mockInterviewsPerMonth",
  },
  {
    key: "interview_academy",
    name: "Interview Academy",
    description: "Learn interview strategy, STAR responses, and confidence systems.",
    enabled: true,
    requiredTier: "pro",
  },
  {
    key: "cover_letter_generator",
    name: "Cover Letter Generator",
    description: "Generate role-specific cover letters and application messaging.",
    enabled: true,
    requiredTier: "pro",
    usageLimitKey: "aiCreditsPerMonth",
  },
  {
    key: "linkedin_optimizer",
    name: "LinkedIn Optimizer",
    description: "Improve recruiter visibility and profile positioning.",
    enabled: true,
    requiredTier: "pro",
    usageLimitKey: "aiCreditsPerMonth",
  },
  {
    key: "networking_outreach",
    name: "Networking Outreach",
    description: "Plan recruiter outreach, networking messages, and follow-ups.",
    enabled: true,
    requiredTier: "pro",
    usageLimitKey: "aiCreditsPerMonth",
  },
  {
    key: "analytics_dashboard",
    name: "Analytics Dashboard",
    description: "Review application metrics, usage trends, and career progress.",
    enabled: true,
    requiredTier: "pro",
  },
  {
    key: "career_coach",
    name: "Career Coach",
    description: "Receive AI-guided career planning and job-search recommendations.",
    enabled: true,
    requiredTier: "premium",
    usageLimitKey: "aiCreditsPerMonth",
  },
  {
    key: "salary_intelligence",
    name: "Salary Intelligence",
    description: "Review compensation guidance and negotiation preparation.",
    enabled: true,
    requiredTier: "premium",
  },
  {
    key: "portfolio_builder",
    name: "Portfolio Builder",
    description: "Build career portfolios and supporting proof-of-work materials.",
    enabled: true,
    requiredTier: "premium",
  },
  {
    key: "seo_blog",
    name: "SEO Blog",
    description: "Manage content and search visibility for future growth workflows.",
    enabled: true,
    requiredTier: "business",
  },
  {
    key: "billing_manager",
    name: "Billing Manager",
    description: "Review billing, membership status, usage, and subscription actions.",
    enabled: true,
    requiredTier: "free",
  },
  {
    key: "admin_tools",
    name: "Admin Tools",
    description: "Owner controls for the Crestpoint platform.",
    enabled: true,
    requiredTier: "admin",
  },
]
